var schools = {
msi: {school: 'Madhrasathul Sheikh Ibrahim - GS78', trainer: 'Fazil'},
gbs: {school: 'Gaazee Bandaarain School - GS39', trainer: 'Fazil'},
msat: {school: 'Madhrasathul Shaheed Ali Thakurufuanu School - GS87', trainer: 'Fazil'},
sobaahschool: {school: 'Filladhoo School - GS85', trainer: 'Fazil'},
haaec: {school: 'Ha. Atoll Education Centre - GS08', trainer: 'Fazil'},
haatollschool: {school: 'Ha. Atoll school - GS19', trainer: 'Fazil'},
ihavandhooschool: {school: 'Ihavandhoo School - GS79', trainer: 'Fazil'},
baarashuschool: {school: 'Baarashu School - GS76', trainer: 'Fazil'},
maarandhooschool: {school: 'Maarandhoo School - GS82', trainer: 'Fazil'},
vashafaruschool: {school: 'Vasahfaru School - GS81', trainer: 'Fazil'},
molhadhooschool: {school: 'Molhadhoo School - GS84', trainer: 'Fazil'},
muraidhooschool: {school: 'Muraidhoo School - GS83', trainer: 'Fazil'},
thuraakunuschool: {school: 'Thuraakunu School - GS86', trainer: 'Fazil'},
uligamuschool: {school: 'Uligamu School - GS80', trainer: 'Fazil'},
afeefuddin: {school: 'Afeefudin School - GS72', trainer: 'Fazil'},
jalaluddin: {school: 'Jalaaludin school - GS53', trainer: 'Fazil'},
hdhaec: {school: 'Hdh.Atoll Education Centre - GS02', trainer: 'Fazil'},
hdhatollschool: {school: 'Hdh.Atoll School - GS20', trainer: 'Fazil'},
hanimaadhooschool: {school: 'Hanimaadhoo School - GS60', trainer: 'Fazil'},
fineyschool: {school: 'Finey School - GS99', trainer: 'Fazil'},
kumundhooschool: {school: 'Kumundhoo School - GS96', trainer: 'Fazil'},
kurinbeeschool: {school: 'Kurinbee School - GS95', trainer: 'Fazil'},
naivaadhooschool: {school: 'Navaidhoo School - GS92', trainer: 'Fazil'},
nolhivaramschool: {school: 'Nolhivaram School - GS90', trainer: 'Fazil'},
hirimaradhooschool: {school: 'Hirimaradhoo School - GS88', trainer: 'Fazil'},
makunudhooschool: {school: 'Makunudhoo School - GS97', trainer: 'Fazil'},
nellaidhooschool: {school: 'Nellaidhoo School - GS93', trainer: 'Fazil'},
neykurendhooschool: {school: 'Neykurendhoo School - GS91', trainer: 'Fazil'},
nolhivaranfaruschool: {school: 'Nolhivaranfaru School - GS89', trainer: 'Fazil'},
munavvara: {school: 'Munavvara School - GS212', trainer: 'Fazil'},
shaec: {school: 'Sh. Atoll Education Centre - GS9', trainer: 'Ahsan'},
shatollschool: {school: 'Sh. Atoll School - GS34', trainer: 'Ahsan'},
feevakuschool: {school: 'Feevaku School - GS108', trainer: 'Anees'},
foakaidhooschool: {school: 'Foakaidhoo School - GS107', trainer: 'Anees'},
milandhooschool: {school: 'Milandhoo School - GS69', trainer: 'Anees'},
bileffaheeschool: {school: 'Bileyfahee School - GS103', trainer: 'Anees'},
shfeydhooschool: {school: 'Feydhoo School - GS109', trainer: 'Anees'},
shgoidhooschool: {school: 'Goidhoo School - GS110', trainer: 'Fazil'},
lhaimaguschool: {school: 'Lhaimagu School - GS104', trainer: 'Anees'},
narudhooschool: {school: 'Narudhoo School - GS101', trainer: 'Anees'},
noomaraaschool: {school: 'Noomaraa School - GS102', trainer: 'Anees'},
funadhooschool: {school: 'Funadhoo School - GS59', trainer: 'Anees'},
maaungoodhooschool: {school: 'Maaungoodhoo School - GS106', trainer: 'Anees'},
naec: {school: 'N. Atoll Education Centre - GS07', trainer: 'Anees'},
natollschool: {school: 'N. Atoll school - GS35', trainer: 'Anees'},
fodhdhooschool: {school: 'Fodhdhoo School - GS118', trainer: 'Anees'},
henbadhooschool: {school: 'Henbadhoo School - GS111', trainer: 'Anees'},
meyna: {school: 'Meyna School - GS47', trainer: 'Anees'},
kendhikulhudhooschool: {school: 'Kendhikulhudhoo School - GS67', trainer: 'Anees'},
kudafareeschool: {school: 'Kudafaree School - Gs113', trainer: 'Anees'},
landhooschool: {school: 'Landhoo School - GS119', trainer: 'Anees'},
lhoheeschool: {school: 'Lhohee School - GS112', trainer: 'Anees'},
maafaruschool: {school: 'Maafaru Schoool - GS115', trainer: 'Anees'},
maalhendhooschool: {school: 'Maalhendhoo School - GS114', trainer: 'Anees'},
nmagoodhooschool: {school: 'Magoodhoo School - GS117', trainer: 'Anees'},
hidhayaschool: {school: 'Hidhaya School - GS116', trainer: 'Anees'},
raec: {school: 'R. Atoll Education Centre - GS15', trainer: 'Anees'},
ratollschool: {school: 'R. Atoll school - GS18', trainer: 'Anees'},
angolhitheemuschool: {school: 'Angolhitheemu School - GS125', trainer: 'Anees'},
fainuschool: {school: 'Fainu School - GS129', trainer: 'Anees'},
inguraidhooschool: {school: 'Inguraidhoo School - GS124', trainer: 'Anees'},
innamaadhooschool: {school: 'Innamaadhoo School - GS123', trainer: 'Anees'},
kinolhahuschool: {school: 'Kinolhahu School - GS122', trainer: 'Anees'},
maakurathuschool: {school: 'Maakurathu School - GS127', trainer: 'Anees'},
rasgetheemuschool: {school: 'Rasgetheemu School - GS121', trainer: 'Firash'},
rasmaadhooschool: {school: 'Rasmaadhoo School - GS120', trainer: 'Firash'},
alifushischool: {school: 'Alifushi School - GS68', trainer: 'Firash'},
ungoofaaruschool: {school: 'Ungoofaaru School - GS210', trainer: 'Firash'},
hulhudhuffaaruschool: {school: 'Hulhudhuffaaru School - GS57', trainer: 'Firash'},
rvaadhooschool: {school: 'Vaadhoo School - GS126', trainer: 'Firash'},
rmaduvvareeschool: {school: 'Maduvvaree School - GS128', trainer: 'Firash'},
dhuvaafaruprimaryschool: {school: 'Duvaafaru Primary School - GS213', trainer: 'Firash'},
baec: {school: 'B.Atoll Eduction Centre - GS01', trainer: 'Firash'},
batollschool: {school: 'B.Atoll School - GS33', trainer: 'Firash'},
dhonfanuschool: {school: 'Dhonfanu School - GS138', trainer: 'Firash'},
fulhadhooschool: {school: 'Fulhadhoo School - GS137', trainer: 'Firash'},
bgoidhooschool: {school: 'Goidhoo School - GS139', trainer: 'Firash'},
hithaadhooschool: {school: 'Hithaadhoo School - GS130', trainer: 'Firash'},
kamadhooschool: {school: 'Kamadhoo School - GS133', trainer: 'Firash'},
kendhooschool: {school: 'Kendhoo School - GS132', trainer: 'Firash'},
kihaadhooschool: {school: 'Kihaadhoo School - GS131', trainer: 'Firash'},
kudarikiluschool: {school: 'Kudarikil School - GS134', trainer: 'Firash'},
bmaalhohuschool: {school: 'Maalhohu School - GS135', trainer: 'Firash'},
thulhaadhooschool: {school: 'Thulhaadhoo School - GS56', trainer: 'Firash'},
lhaec: {school: 'Lh. Atoll Education Centre - GS22', trainer: 'Ahsan'},
lhatollschool: {school: 'Lh. Atoll school - GS21', trainer: 'Ahsan'},
olhuvelifushischool: {school: 'Olhuvelifushi School - GS140', trainer: 'Firash'},
ifthithaah: {school: 'Madrasathul Ifthithaah - GS51', trainer: 'Shamoon'},
kaec: {school: 'K. Atoll Education Centre - GS14', trainer: 'Saud'},
katollschool: {school: 'K. Atoll School - GS36', trainer: 'Shamoon'},
maafushischool: {school: 'Maafushee School - GS143', trainer: 'Anees'},
huraaschool: {school: 'Huraa School - GS142', trainer: 'Ahsan'},
himmafushischool: {school: 'Himmafushee School - GS141', trainer: 'Ahsan'},
kguraidhooschool: {school: 'Guraidhoo School - GS145', trainer: 'Shamoon'},
gaafaruschool: {school: 'Gaafaru School - GS147', trainer: 'Shamoon'},
dhiffushischool: {school: 'Dhiffushi School - GS144', trainer: 'Shamoon'},
gulheeschool: {school: 'Gulhi School - GS146', trainer: 'Shamoon'},
aaaec: {school: 'Aa. Atoll Education Centre - GS40', trainer: 'Shamoon'},
aaatollschool: {school: 'Aa. Atoll School - GS32', trainer: 'Shamoon'},
ukulhahuschool: {school: 'Ukulhahu School - GS150', trainer: 'Shamoon'},
thoddooschool: {school: 'Thoddu School - GS66', trainer: 'Shamoon'},
mathiverischool: {school: 'Mathiveri School - GS152', trainer: 'Shamoon'},
bodufolhudhooschool: {school: 'Bodufolhudhoo School - GS149', trainer: 'Shamoon'},
aamaalhohuschool: {school: 'Maalhohu School - GS151', trainer: 'Shamoon'},
himandhooschool: {school: 'Himandhoo School - GS148', trainer: 'Shamoon'},
adhaec: {school: 'ADh. Atoll Education Centre - GS10', trainer: 'Shamoon'},
adhatollschool: {school: 'ADh. Atoll School - GS42', trainer: 'Shamoon'},
hangnaameedhooschool: {school: 'Hangnaameedhoo School - GS153', trainer: 'Shamoon'},
adhomadhooschool: {school: 'Omadhoo School - GS155', trainer: 'Shamoon'},
kunburudhooschool: {school: 'Kunburudhoo School - GS154', trainer: 'Shamoon'},
mandhooschool: {school: 'Mandhoo School - GS156', trainer: 'Shamoon'},
dhangethischool: {school: 'Dhangethee School - GS158', trainer: 'Shamoon'},
adhdhidhooschool: {school: 'Dhidhdhoo School - GS159', trainer: 'Shamoon'},
dhigurahschool: {school: 'Dhigurah School - GS160', trainer: 'Shamoon'},
fenfusheeschool: {school: 'Fenfushee School - GS157', trainer: 'Ahsan'},
vaec: {school: 'V. Atoll Education Centre - GS38', trainer: 'Shamoon'},
vatollschool: {school: 'V.Atoll School - GS12', trainer: 'Shamoon'},
keyodhooschool: {school: 'Keyodhoo School - GS70', trainer: 'Shamoon'},
maec: {school: 'M.Atoll Education Center - GS23', trainer: 'Shamoon'},
matollschool: {school: 'M. Atoll School - GS25', trainer: 'Shamoon'},
mulakuschool: {school: 'Mulaku School - GS166', trainer: 'Shamoon'},
dhiggaruschool: {school: 'Dhiggaru School - GS168', trainer: 'Shamoon'},
raiymandhooschool: {school: 'Riymandhoo School - GS164', trainer: 'Shamoon'},
veyvashuschool: {school: 'Veyvashu School - GS165', trainer: 'Shamoon'},
naalaafushischool: {school: 'Naalaafushi School - GS163', trainer: 'Shamoon'},
mmaduvvareeschool: {school: 'Maduvvary School - GS167', trainer: 'Shamoon'},
faec: {school: 'F. Atoll Education Centre - GS37', trainer: 'Ahsan'},
fatollschool: {school: 'F. Atoll School - GS11', trainer: 'Ahsan'},
fmagoodhooschool: {school: 'Magoodhoo School - GS71', trainer: 'Ahsan'},
bilehdhooschool: {school: 'Bileiydhoo School - GS169', trainer: 'Ahsan'},
dharanboodhooschool: {school: 'Dharanboodhoo School - GS170', trainer: 'Ahsan'},
dhaec: {school: 'Dh. Atoll Education Centre - GS24', trainer: 'Ahsan'},
dhatollschool: {school: 'Dh. Atoll School - GS31', trainer: 'Ahsan'},
hulhudhelischool: {school: 'Hulhudheli School - GS171', trainer: 'Ahsan'},
rinbudhooschool: {school: 'Rinbudhoo School - GS172', trainer: 'Ahsan'},
bandidhooschool: {school: 'Bandidhoo School - GS173', trainer: 'Ahsan'},
maaenboodhooschool: {school: 'Maaenboodhoo Madhrasa - GS175', trainer: 'Ahsan'},
thaec: {school: 'Th. Atoll Education Centre - GS04', trainer: 'Ahsan'},
thatollschool: {school: 'Th. Atoll School - GS27', trainer: 'Ahsan'},
dhiyamigilischool: {school: 'Dhiyamigili School - GS181', trainer: 'Saud'},
kinbidhooschool: {school: 'Kinbidhoo School - GS55', trainer: 'Saud'},
veymandooschool: {school: 'Veymandoo School - GS63', trainer: 'Saud'},
hirilandhooschool: {school: 'Hirilandhoo School - GS64', trainer: 'Saud'},
vilufusheeschool: {school: 'Vilufushee School - GS65', trainer: 'Saud'},
buruneeschool: {school: 'Burunee School - GS176', trainer: 'Saud'},
kandoodhooschool: {school: 'Kandoodhoo School - GS177', trainer: 'Saud'},
vandhooschool: {school: 'Vandhoo School - GS179', trainer: 'Saud'},
madifushischool: {school: 'Madifushi School - GS180', trainer: 'Saud'},
thomadhooschool: {school: 'Omadhoo School - GS178', trainer: 'Saud'},
gaadhiffushischool: {school: 'Gaadhiffushi School - GS182', trainer: 'Saud'},
laec: {school: 'L. Atoll Education Centre - GS17', trainer: 'Saud'},
latollschool: {school: 'L. Atoll School - GS28', trainer: 'Saud'},
maavashuschool: {school: 'Maavashu School - GS49', trainer: 'Saud'},
hamadschool: {school: 'Hamad Bin Khaleefa Al Saanee - GS52', trainer: 'Saud'},
lhithadhooschool: {school: 'Hithadhoo School - GS183', trainer: 'Saud'},
kunahandhooschool: {school: 'Kunahandhoo School - GS184', trainer: 'Saud'},
isdhooschool: {school: 'Isdhoo School - GS186', trainer: 'Saud'},
isdhookalaidhooschool: {school: 'Isdhookalhaidhoo School - GS187', trainer: 'Saud'},
mundooschool: {school: 'Mundoo School - GS188', trainer: 'Saud'},
lmaamendhooschool: {school: 'Maamendhoo School - GS189', trainer: 'Saud'},
dhanbidhooschool: {school: 'Dhanbidhoo School - GS190', trainer: 'Saud'},
mukurimaguschool: {school: 'Mukurimagu School - GS191', trainer: 'Saud'},
ihadhdhooschool: {school: 'Ihadhdhoo School - GS215', trainer: 'Saud'},
gaaec: {school: 'G.A. Atoll Education Centre - GS05', trainer: 'Saud'},
gaatollschool: {school: 'G.A. Atoll School - GS29', trainer: 'Saud'},
ganilandhooschool: {school: 'Nilandhoo School - GS195', trainer: 'Saud'},
kondeyschool: {school: 'Konday School - GS196', trainer: 'Saud'},
kanduhulhudhooschool: {school: 'Kanduhulhudhoo School - GS197', trainer: 'Saud'},
gamaamendhooschool: {school: 'Maamendhoo School - GS198', trainer: 'Saud'},
dhaandhooschool: {school: 'Dhaandhoo School - GS199', trainer: 'Saud'},
msm: {school: 'Madhrasathul Sulthan Mohamed - GS200', trainer: 'Mihad'},
gemanafushischool: {school: 'Gemanafushi School - GS202', trainer: 'Mihad'},
gdhaec: {school: 'G.Dh Atoll Education Centre - GS26', trainer: 'Mihad'},
gdhatollschool: {school: 'G.Dh Atoll School - GS30', trainer: 'Mihad'},
aboobakuruschool: {school: 'Aboobakuru School - GS73', trainer: 'Mihad'},
hoadedhdhooschool: {school: 'Hoadedhdhoo School - GS203', trainer: 'Mihad'},
nadellaschool: {school: 'Nadella School - GS204', trainer: 'Mihad'},
rathafandhooschool: {school: 'Rathafandhoo School - GS205', trainer: 'Mihad'},
vjs: {school: 'Vaadhoo Jamaluddeen School - GS206', trainer: 'Mihad'},
madavelischool: {school: 'Madaveli School - GS207', trainer: 'Mihad'},
huvadhooschool: {school: 'Huvadhoo School - GS208', trainer: 'Mihad'},
fiyoareeschool: {school: 'Fiyoari School - GS209', trainer: 'Mihad'},
thinadhooschool: {school: 'Thinadhoo School - GS216', trainer: 'Mihad'},
gnaec: {school: 'Gn. Atoll Education Centre - GS13', trainer: 'Firash'},
fuvahmulakuschool: {school: 'Fuvahmulaku School - GS44', trainer: 'Firash'},
mjm: {school: 'MJM - GS48', trainer: 'Firash'},
hafizahmed: {school: 'Hafiz Ahmed School - GS74', trainer: 'Firash'},
sharafuddin: {school: 'Sharafudheen School - GS43', trainer: 'Firash'},
hithadhooschool: {school: 'Hithadhoo School - GS03', trainer: 'Mihad'},
nooraaneeschool: {school: 'Nooranee School - GS211', trainer: 'Mihad'},
ahs: {school: 'Addu High School - GS58', trainer: 'Mihad'},
maradhooschool: {school: 'Maradhoo School - GS62', trainer: 'Mihad'},
mfs: {school: 'Maradhoo Feydhoo School - GS61', trainer: 'Mihad'},
irushadhiyya: {school: 'Irushaadhiyya School - GS41', trainer: 'Mihad'},
feydhooschool: {school: 'Feydhoo School - GS45', trainer: 'Mihad'},
satollschool: {school: 'S. Atoll School - GS16', trainer: 'Mihad'},
iskandhar: {school: 'Iskandharu School - IS', trainer: 'Waheed'},
jamaluddin: {school: 'Jamaluddin School - JS', trainer: 'Waheed'},
kalaafaanuschool: {school: 'Kalaafaanu School - KS', trainer: 'Waheed'},
thaajuddeenschool: {school: 'Thaajuddeen school - TS', trainer: 'Waheed'},
imaduddin: {school: 'Imaduddin School - IM', trainer: 'Waheed'},
aminiya: {school: 'Aminiya School - AS', trainer: 'Waheed'},
majeediyya: {school: 'Majeediyya School - MS', trainer: 'Waheed'},
dharuma: {school: 'Dharumavantha School - DS', trainer: 'Waheed'},
hiriya: {school: 'Hiriyaa School - HS', trainer: 'Waheed'},
muhyiddin: {school: 'Muhyiddin School - MUH', trainer: 'Waheed'},
ghaazee: {school: 'Ghaazee School - GS', trainer: 'Ahsan'},
chse: {school: 'Centre for Higher Secondary Education - CHSE', trainer: 'Saud'},
arabiyya: {school: 'Al Madharusathul Arabiyyathul Islaamiyya - MAI', trainer: 'Mihad'},
rehendi: {school: 'Rehendhi School - RS', trainer: 'Ahsan'},
huravee: {school: 'Huravee School - HUR', trainer: 'Ahsan'},
izzudhdheen: {school: 'I\'zzudhdheen School - IZS', trainer: 'Ahsan'}
}
localStorage.setItem('schoolData', JSON.stringify(schools));